stock:
  code:
    strLength: 6
    range:
      from: 2672
      to: 2981
      plate: SZ
    filePath: ./stockCode.txt

report:
  file:
    list:
      queryUrl: http://www.cninfo.com.cn/new/hisAnnouncement/query
    download:
      baseUrl: http://static.cninfo.com.cn/
    savePath: /Users/sunrise2075/Documents/张翰清博士数据/2018中小企业板企业年报
    title:
      whiteList:
          - 2018年年度报告（更新后）
          - 2018年年度报告（更正版）
          - 2018年年度报告（更新版）
          - 2018年年度报告（2019年修订）
          - 2018年年度报告（修订版）
          - 2018年年度报告（更正）
          - 2018年年度报告
      blackList:
          - H股公告-2018年年度报告
          - 2018年年度报告（已取消）
          - 2018年年度报告（英文版）
          - 2018年年度报告摘要
          - 2018年年度报告摘要（英文版）
          - 2018年年度报告摘要（修订版）
          - 2018年年度报告摘要（更新后）
          - 2018年年度报告摘要（已取消）
          - 2018年年度报告（印刷版）
          - 2018年年度报告（修订版）
          - 2018年年度报告（修订稿）
          - 2018年年度报告（修订后）
          - 关于公司2018年年度报告修订说明
          - 2018年年度报告摘要
          - 2018年年度报告摘要（更正）
          - 2018年年度报告摘要（修订后）
          - 2018年半年度报告
          - 2018年半年度报告（2019年修订）