cninfo:
  stock:
    code:
      length: 6
      range:
        from: 1
        to: 1
      filePath: ./stockCode.txt

  report:
    file:
      list:
        queryUrl: http://www.cninfo.com.cn/new/hisAnnouncement/query
      download:
        baseUrl: http://static.cninfo.com.cn/
      post:
        query:
          tabName: fulltext
          pageNum: 1,
          column: szse
  #        category: category_ndbg_szsh;
          searchkey: 2019年年度报告;
          isHLtitle: true
      savePath: /Users/sunrise2075/Documents/上市公司年报
      title:
        whiteList:
#            - 首次公开发行股票并在创业板上市招股说明书（更新后）
#            - 首次公开发行股票并在创业板上市招股说明书
            - 2019年年度报告（更新后）
            - 2019年年度报告（更正版）
            - 2019年年度报告（更新版）
            - 2019年年度报告（2019年修订）
            - 2019年年度报告（修订版）
            - 2019年年度报告（更正）
            - 2019年年度报告
            - 2019年<em>年度报告</em>
        blackList:
            - H股公告-2019年年度报告
            - 2019年年度报告（已取消）
            - 2019年年度报告（英文版）
            - 2019年年度报告摘要
            - 2019年年度报告摘要（英文版）
            - 2019年年度报告摘要（修订版）
            - 2019年年度报告摘要（更新后）
            - 2019年年度报告摘要（已取消）
            - 2019年年度报告（印刷版）
            - 2019年年度报告（修订版）
            - 2019年年度报告（修订稿）
            - 2019年年度报告（修订后）
            - 关于公司2019年年度报告修订说明
            - 2019年年度报告摘要
            - 2019年年度报告摘要（更正）
            - 2019年年度报告摘要（修订后）
            - 2019年半年度报告
            - 2019年半年度报告（2019年修订）